# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            'Swift Bits'
tagline:          'A Place for Handy Swift Snippets'
description:      'Code snippets, styles and ideals on my journey from Obj-C to Swift.'
url:              https://mfclarke.github.io
baseurl:          /

author:
  name:           'Maximilian Clarke'
  url:            https://twitter.com/mfc83_

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/mfclarke/mfclarke.github.io
