# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            'Swift Bits'
tagline:          'All things Swift'
description:      "<a href='https://twitter.com/mfc83_' target='_blank'>@mfc83_</a>'s Swift stuff. I also run <a href='http://trainspottr.fm' target='_blank'>trainspottr.fm</a>"
url:              https://mfclarke.github.io
baseurl:          /

author:
  name:           'Maximilian Clarke'
  url:            https://twitter.com/mfc83_

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/mfclarke/mfclarke.github.io

kramdown:
  input: GFM
  syntax_highlighter: rouge

gems: [jekyll-paginate]
