# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Swift Bits
tagline:          'Handy snippets as I transition from ObjC to Swift'
description:      'As I make the transition to Swift, I'm noticing a lot of handy pieces of code or tidbits of knowledge. This site will be a store for all these 'remember me' bits.'
url:              http://mfclarke.github.io
baseurl:          /

author:
  name:           'Maximilian Clarke'

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/mfclarke/mfclarke.github.io
